version: '3'
services:
  node:
    build: .
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    env_file:
      .env
    networks:
      - my-network
  postgres:
    build: ./src/database
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - logsdata:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  logsdata:
  dbdata: