version: '3'
services:
  node:
    build: .
    image: 9fogel/docker-hl-node
    restart: always
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    env_file:
      .env
    networks:
      - my-network
  postgres:
    build: ./src/database
    image: 9fogel/hl-postgres
    container_name: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - logsdata:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      PGDATA: ${PGDATA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  logsdata:
  dbdata: